{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
     "cell_type": "markdown",
     "metadata": {
      "colab_type": "text",
      "id": "view-in-github"
     },
     "source": [
      "<a href=\"https://colab.research.google.com/github/adrian-alejandro/autoML/blob/main/AutoML_Practico_2.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
     ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install optuna"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "PTKRtk9t0ikT",
        "outputId": "3e252fcb-eb89-44b4-de18-160cfaae9599"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Collecting optuna\n",
            "  Downloading optuna-3.0.4-py3-none-any.whl (348 kB)\n",
            "\u001b[K     |████████████████████████████████| 348 kB 5.2 MB/s \n",
            "\u001b[?25hRequirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from optuna) (1.4.44)\n",
            "Collecting alembic>=1.5.0\n",
            "  Downloading alembic-1.8.1-py3-none-any.whl (209 kB)\n",
            "\u001b[K     |████████████████████████████████| 209 kB 48.3 MB/s \n",
            "\u001b[?25hRequirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from optuna) (1.21.6)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from optuna) (21.3)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from optuna) (4.64.1)\n",
            "Collecting cliff\n",
            "  Downloading cliff-4.1.0-py3-none-any.whl (81 kB)\n",
            "\u001b[K     |████████████████████████████████| 81 kB 10.4 MB/s \n",
            "\u001b[?25hRequirement already satisfied: PyYAML in /usr/local/lib/python3.8/dist-packages (from optuna) (6.0)\n",
            "Requirement already satisfied: scipy<1.9.0,>=1.7.0 in /usr/local/lib/python3.8/dist-packages (from optuna) (1.7.3)\n",
            "Collecting cmaes>=0.8.2\n",
            "  Downloading cmaes-0.9.0-py3-none-any.whl (23 kB)\n",
            "Requirement already satisfied: importlib-metadata<5.0.0 in /usr/local/lib/python3.8/dist-packages (from optuna) (4.13.0)\n",
            "Collecting colorlog\n",
            "  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)\n",
            "Requirement already satisfied: importlib-resources in /usr/local/lib/python3.8/dist-packages (from alembic>=1.5.0->optuna) (5.10.0)\n",
            "Collecting Mako\n",
            "  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)\n",
            "\u001b[K     |████████████████████████████████| 78 kB 8.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata<5.0.0->optuna) (3.11.0)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=20.0->optuna) (3.0.9)\n",
            "Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/dist-packages (from sqlalchemy>=1.3.0->optuna) (2.0.1)\n",
            "Collecting stevedore>=2.0.1\n",
            "  Downloading stevedore-4.1.1-py3-none-any.whl (50 kB)\n",
            "\u001b[K     |████████████████████████████████| 50 kB 6.5 MB/s \n",
            "\u001b[?25hCollecting autopage>=0.4.0\n",
            "  Downloading autopage-0.5.1-py3-none-any.whl (29 kB)\n",
            "Requirement already satisfied: PrettyTable>=0.7.2 in /usr/local/lib/python3.8/dist-packages (from cliff->optuna) (3.5.0)\n",
            "Collecting cmd2>=1.0.0\n",
            "  Downloading cmd2-2.4.2-py3-none-any.whl (147 kB)\n",
            "\u001b[K     |████████████████████████████████| 147 kB 64.2 MB/s \n",
            "\u001b[?25hRequirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.8/dist-packages (from cmd2>=1.0.0->cliff->optuna) (0.2.5)\n",
            "Collecting pyperclip>=1.6\n",
            "  Downloading pyperclip-1.8.2.tar.gz (20 kB)\n",
            "Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.8/dist-packages (from cmd2>=1.0.0->cliff->optuna) (22.1.0)\n",
            "Collecting pbr!=2.1.0,>=2.0.0\n",
            "  Downloading pbr-5.11.0-py2.py3-none-any.whl (112 kB)\n",
            "\u001b[K     |████████████████████████████████| 112 kB 56.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.8/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.0.1)\n",
            "Building wheels for collected packages: pyperclip\n",
            "  Building wheel for pyperclip (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11136 sha256=693144866aa0d0dc10c8917330f6209c6003f6d33e222395813ded24ea4897fa\n",
            "  Stored in directory: /root/.cache/pip/wheels/7f/1a/65/84ff8c386bec21fca6d220ea1f5498a0367883a78dd5ba6122\n",
            "Successfully built pyperclip\n",
            "Installing collected packages: pyperclip, pbr, stevedore, Mako, cmd2, autopage, colorlog, cmaes, cliff, alembic, optuna\n",
            "Successfully installed Mako-1.2.4 alembic-1.8.1 autopage-0.5.1 cliff-4.1.0 cmaes-0.9.0 cmd2-2.4.2 colorlog-6.7.0 optuna-3.0.4 pbr-5.11.0 pyperclip-1.8.2 stevedore-4.1.1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 47,
      "metadata": {
        "id": "0OsAd-Gyq7xp"
      },
      "outputs": [],
      "source": [
        "import os\n",
        "from io import BytesIO\n",
        "import requests\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import optuna\n",
        "\n",
        "from sklearn import datasets\n",
        "from sklearn import model_selection\n",
        "from sklearn import svm, naive_bayes, linear_model\n",
        "from sklearn.metrics import balanced_accuracy_score, make_scorer"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "vectorized_dataset_url = \"https://raw.githubusercontent.com/adrian-alejandro/Busqueda-y-Recomendacion-para-Textos-Legales-Mentoria-2022/main/embeddings/vectorized_dataset_X_y.npz\"\n",
        "processed_data_url = \"https://raw.githubusercontent.com/adrian-alejandro/Busqueda-y-Recomendacion-para-Textos-Legales-Mentoria-2022/main/embeddings/processed_dataset.csv\""
      ],
      "metadata": {
        "id": "I4q9JKtJreLg"
      },
      "execution_count": 40,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "vector_file = os.path.split(vectorized_dataset_url)[1]\n",
        "dataset = os.path.split(processed_data_url)[1]"
      ],
      "metadata": {
        "id": "Xm3LnCBuDE4w"
      },
      "execution_count": 32,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def read_npz_from_url(url):\n",
        "  \"\"\"Function that reads a npz file from a URL and overrides np.load method to\n",
        "   force allow_pickle.\n",
        "   Ref: https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa\n",
        "  \"\"\"\n",
        "  # save np.load\n",
        "  np_load_old = np.load\n",
        "\n",
        "  # modify the default parameters of np.load\n",
        "  np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)\n",
        "\n",
        "  r = requests.get(url, stream=True)\n",
        "\n",
        "  # call load_data with allow_pickle implicitly set to true\n",
        "  vectors = np.load(BytesIO(r.raw.read()))\n",
        "\n",
        "  # restore np.load for future normal usage\n",
        "  np.load = np_load_old\n",
        "\n",
        "  return vectors"
      ],
      "metadata": {
        "id": "uhPXcOUHGhuE"
      },
      "execution_count": 45,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "vectors = read_npz_from_url(vectorized_dataset_url)\n",
        "\n",
        "# Texto vectorizado\n",
        "X = vectors['X']\n",
        "                                            \n",
        "\n",
        "# Etiquetas (fueros)\n",
        "y = vectors['y']"
      ],
      "metadata": {
        "id": "DT2kfIEMr9sW"
      },
      "execution_count": 46,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "data = pd.read_csv(processed_data_url, sep='|', encoding='utf-8')\n",
        "data.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 206
        },
        "id": "ikXTQ2tNCxBm",
        "outputId": "aa28b9e0-f732-4585-97e9-1df608b6dc76"
      },
      "execution_count": 39,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                                             archivo    fuero  \\\n",
              "0                          9 BAEZ-FLECHA BUS.pdf.txt  LABORAL   \n",
              "1                            90 FUNES-COYSPU.pdf.txt  LABORAL   \n",
              "2                     1 QUINTEROS-CONSOLIDAR.pdf.txt  LABORAL   \n",
              "3  3 SANGUEDOLCE-MUNICIPALIDAD DE VILLA ALLENDE.p...  LABORAL   \n",
              "4                        188 LUCIANO-NICOLAS.pdf.txt  LABORAL   \n",
              "\n",
              "                                         texto_clean  \n",
              "0  ['sala', 'laboral', 'tribunal', 'superior', 'p...  \n",
              "1  ['sala', 'laboral', 'tribunal', 'superior', 'p...  \n",
              "2  ['sala', 'laboral', 'tribunal', 'superior', 'p...  \n",
              "3  ['sala', 'laboral', 'tribunal', 'superior', 'p...  \n",
              "4  ['sala', 'laboral', 'tribunal', 'superior', 'p...  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-b7da4d5b-c3f9-4266-a6bd-3a4f827c0bf6\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>archivo</th>\n",
              "      <th>fuero</th>\n",
              "      <th>texto_clean</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>9 BAEZ-FLECHA BUS.pdf.txt</td>\n",
              "      <td>LABORAL</td>\n",
              "      <td>['sala', 'laboral', 'tribunal', 'superior', 'p...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>90 FUNES-COYSPU.pdf.txt</td>\n",
              "      <td>LABORAL</td>\n",
              "      <td>['sala', 'laboral', 'tribunal', 'superior', 'p...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1 QUINTEROS-CONSOLIDAR.pdf.txt</td>\n",
              "      <td>LABORAL</td>\n",
              "      <td>['sala', 'laboral', 'tribunal', 'superior', 'p...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3 SANGUEDOLCE-MUNICIPALIDAD DE VILLA ALLENDE.p...</td>\n",
              "      <td>LABORAL</td>\n",
              "      <td>['sala', 'laboral', 'tribunal', 'superior', 'p...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>188 LUCIANO-NICOLAS.pdf.txt</td>\n",
              "      <td>LABORAL</td>\n",
              "      <td>['sala', 'laboral', 'tribunal', 'superior', 'p...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-b7da4d5b-c3f9-4266-a6bd-3a4f827c0bf6')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-b7da4d5b-c3f9-4266-a6bd-3a4f827c0bf6 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-b7da4d5b-c3f9-4266-a6bd-3a4f827c0bf6');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 39
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Step 1. Define an objective function to be maximized.\n",
        "def objective(trial):\n",
        "\n",
        "    classifier_name = trial.suggest_categorical(\"classifier\", [\"LogReg\", \"SVM\", \"MNB\"])\n",
        "    \n",
        "    # Step 2. Setup values for the hyperparameters:\n",
        "    if classifier_name == 'LogReg':\n",
        "      # Seach space\n",
        "      logreg_c = trial.suggest_float(\"logreg_c\", 1e-10, 1e10, log=True)\n",
        "      logreg_solver = trial.suggest_categorical(\"logreg_solver\", ['newton-cg', 'lbfgs', 'sag', 'saga'])\n",
        "      logreg_fit_intercept = trial.suggest_categorical(\"logreg_intercept\", [False, True])\n",
        "      logreg_penalty = trial.suggest_categorical(\"logreg_penalty\", ['l1', 'l2', 'elasticnet', 'none'])\n",
        "      # Estimator\n",
        "      classifier_obj = linear_model.LogisticRegression(\n",
        "          C=logreg_c,\n",
        "          solver=logreg_solver,\n",
        "          fit_intercept=logreg_fit_intercept,\n",
        "          penalty=logreg_penalty)\n",
        "    elif classifier_name == \"SVM\":\n",
        "      # Search space\n",
        "      svm_c = trial.suggest_float(\"svm_c\", 1e-1, 1e1)\n",
        "      svm_kernel = trial.suggest_categorical(\"svm_kernel\", ['poly', 'linear', 'rbf', 'sigmoid'])\n",
        "      svm_gamma = trial.suggest_categorical(\"svm_gamma\", ['scale', 'auto'])\n",
        "      svm_shrinking = trial.suggest_categorical(\"svm_shrinking\", [True, False])\n",
        "      svm_break_ties = trial.suggest_categorical(\"svm_break_ties\", [True, False])\n",
        "      svm_decision_function_shape = trial.suggest_categorical(\"svm_decision_function_shape\", ['ovo', 'ovr'])\n",
        "      # Estimator\n",
        "      classifier_obj = svm.SVC(\n",
        "            C=svm_c, \n",
        "            kernel=svm_kernel,\n",
        "            gamma=svm_gamma,\n",
        "            shrinking=svm_shrinking,\n",
        "            break_ties=svm_break_ties,\n",
        "            decision_function_shape=svm_decision_function_shape)\n",
        "    else:\n",
        "      # Search space\n",
        "      mnb_alpha = trial.suggest_float(\"mnb_alpha\", 1e-1, 1e1)\n",
        "      mnb_fit_prior = trial.suggest_categorical(\"mnb_fit_prior\", [True, False])\n",
        "      # Estimator\n",
        "      classifier_obj = naive_bayes.MultinomialNB(\n",
        "          alpha=mnb_alpha,\n",
        "          fit_prior=mnb_fit_prior)\n",
        "\n",
        "    # Step 3: Scoring method:\n",
        "    score = model_selection.cross_val_score(\n",
        "        classifier_obj, \n",
        "        X,\n",
        "        y,\n",
        "        n_jobs=-1,\n",
        "        cv=5,\n",
        "        scoring=make_scorer(balanced_accuracy_score))\n",
        "    balanced_accuracy = score.mean()\n",
        "    return balanced_accuracy\n",
        "\n",
        "study = optuna.create_study(direction=\"maximize\")\n",
        "\n",
        "study.optimize(objective, n_trials=50)\n",
        "\n",
        "\n",
        "best_trial = study.best_trial\n",
        "\n",
        "print(best_trial.params )\n",
        "print(best_trial.value)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "paKRjBks1pI3",
        "outputId": "ce502a67-3276-44fc-ade8-c305a985a7d2"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "\u001b[32m[I 2022-12-10 22:26:36,728]\u001b[0m A new study created in memory with name: no-name-d05652a5-3d6b-4bc0-97ec-1c428e0e4039\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:26:42,105]\u001b[0m Trial 0 finished with value: 0.9630000000000001 and parameters: {'classifier': 'LogReg', 'logreg_c': 19.181756661149585, 'logreg_solver': 'newton-cg', 'logreg_intercept': False, 'logreg_penalty': 'none'}. Best is trial 0 with value: 0.9630000000000001.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:18,302]\u001b[0m Trial 1 finished with value: 0.9713333333333335 and parameters: {'classifier': 'LogReg', 'logreg_c': 4250632642.9724655, 'logreg_solver': 'sag', 'logreg_intercept': False, 'logreg_penalty': 'l2'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:18,583]\u001b[0m Trial 2 finished with value: 0.7134253246753247 and parameters: {'classifier': 'MNB', 'mnb_alpha': 4.9026558464835555, 'mnb_fit_prior': False}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:21,164]\u001b[0m Trial 3 finished with value: 0.25 and parameters: {'classifier': 'SVM', 'svm_c': 2.1005276009028306, 'svm_kernel': 'poly', 'svm_gamma': 'auto', 'svm_shrinking': False, 'svm_break_ties': False, 'svm_decision_function_shape': 'ovr'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:23,721]\u001b[0m Trial 4 finished with value: 0.25 and parameters: {'classifier': 'SVM', 'svm_c': 0.2858362964208204, 'svm_kernel': 'poly', 'svm_gamma': 'auto', 'svm_shrinking': False, 'svm_break_ties': False, 'svm_decision_function_shape': 'ovo'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:23,898]\u001b[0m Trial 5 finished with value: 0.25 and parameters: {'classifier': 'MNB', 'mnb_alpha': 9.369789667947598, 'mnb_fit_prior': True}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[33m[W 2022-12-10 22:27:26,170]\u001b[0m Trial 6 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:26,445]\u001b[0m Trial 7 finished with value: 0.7134253246753247 and parameters: {'classifier': 'MNB', 'mnb_alpha': 3.70679534616171, 'mnb_fit_prior': False}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[33m[W 2022-12-10 22:27:28,231]\u001b[0m Trial 8 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:27:28,423]\u001b[0m Trial 9 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:28,706]\u001b[0m Trial 10 finished with value: 0.25 and parameters: {'classifier': 'MNB', 'mnb_alpha': 8.804071202783396, 'mnb_fit_prior': True}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:31,130]\u001b[0m Trial 11 finished with value: 0.9546666666666667 and parameters: {'classifier': 'SVM', 'svm_c': 5.436197896059324, 'svm_kernel': 'linear', 'svm_gamma': 'scale', 'svm_shrinking': False, 'svm_break_ties': True, 'svm_decision_function_shape': 'ovr'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:27:31,410]\u001b[0m Trial 12 finished with value: 0.7320616883116884 and parameters: {'classifier': 'MNB', 'mnb_alpha': 0.4581494836545619, 'mnb_fit_prior': False}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:28:06,286]\u001b[0m Trial 13 finished with value: 0.961 and parameters: {'classifier': 'LogReg', 'logreg_c': 1468090427.2301188, 'logreg_solver': 'sag', 'logreg_intercept': False, 'logreg_penalty': 'l2'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:28:09,894]\u001b[0m Trial 14 finished with value: 0.9630000000000001 and parameters: {'classifier': 'LogReg', 'logreg_c': 0.0019568483427725276, 'logreg_solver': 'newton-cg', 'logreg_intercept': False, 'logreg_penalty': 'none'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:28:13,514]\u001b[0m Trial 15 finished with value: 0.9630000000000001 and parameters: {'classifier': 'LogReg', 'logreg_c': 574116075.8952678, 'logreg_solver': 'newton-cg', 'logreg_intercept': False, 'logreg_penalty': 'none'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:28:16,676]\u001b[0m Trial 16 finished with value: 0.25 and parameters: {'classifier': 'LogReg', 'logreg_c': 2.1253677241545562e-10, 'logreg_solver': 'sag', 'logreg_intercept': True, 'logreg_penalty': 'l2'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:16,875]\u001b[0m Trial 17 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,075]\u001b[0m Trial 18 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,174]\u001b[0m Trial 19 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,377]\u001b[0m Trial 20 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,580]\u001b[0m Trial 21 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,792]\u001b[0m Trial 22 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:17,994]\u001b[0m Trial 23 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:18,199]\u001b[0m Trial 24 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:18,399]\u001b[0m Trial 25 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 447, in _check_solver\n",
            "    raise ValueError(\n",
            "ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:18,497]\u001b[0m Trial 26 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:18,697]\u001b[0m Trial 27 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "5 fits failed out of a total of 5.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "5 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py\", line 1471, in fit\n",
            "    raise ValueError(\n",
            "ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "\u001b[33m[W 2022-12-10 22:28:18,896]\u001b[0m Trial 28 failed because of the following error: The value nan is not acceptable.\u001b[0m\n",
            "\u001b[32m[I 2022-12-10 22:29:20,632]\u001b[0m Trial 29 finished with value: 0.9693333333333334 and parameters: {'classifier': 'LogReg', 'logreg_c': 78.99250369287363, 'logreg_solver': 'saga', 'logreg_intercept': False, 'logreg_penalty': 'l1'}. Best is trial 1 with value: 0.9713333333333335.\u001b[0m\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from optuna.visualization import plot_optimization_history\n",
        "\n",
        "plot_optimization_history(study).show()\n",
        "\n"
      ],
      "metadata": {
        "id": "q6GIo_CnCbQd"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
